name: Build Compose App

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build MSI
        run: |
          ./gradlew clean build
        shell: bash

      - name: Upload MSI artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: compose-msi
          path: composeApp/build/compose/binaries/main/release/*.msi
