name: Build Compose Desktop App

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-windows-${{ hashFiles('composeApp/**/*.gradle*', 'composeApp/gradle-wrapper.properties') }}
          enableCrossOsArchive: true

      - name: Build MSI
        run: gradlew.bat :composeApp:pa
